// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaajfnohbxveautwjnwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhYWpmbm9oYnh2ZWF1dHdqbnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NDM0NzIsImV4cCI6MjA1MDMxOTQ3Mn0.inu-j24d7gpkS8cOri3-phIIDd1nHT68wbGBJ3dhBk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);